### ISSUE TITLE
How to use with GORM?

### ISSUE THREAD

**Issue by hareku** [tsenart/nap#12]
I want to use nap with `github.com/jinzhu/gorm`.
https://github.com/jinzhu/gorm

I had tried below this code.

```main.go
db, _ := nap.Open("mysql", napConnectionString)
conn, err = gorm.Open("mysql", db)
```

However, I got an error `nvalid database source: {[0xc00019c480] 0} is not a valid type`.

I think it causes that `nap.Stmt.Prepare()` method is different from `go.SQLCommon.Prepare()`.

https://github.com/tsenart/nap/blob/master/db.go#L97
https://github.com/jinzhu/gorm/blob/master/interface.go#L8

How do I solve this?
Thanks.

**Comment by tsenart** [comment]
This is not supposed to work.
