### ISSUE TITLE
db.pdbs[i].SetConnMaxLifetime undefined (type *sql.DB has no field or method SetConnMaxLifetime)

### ISSUE THREAD

**Issue by Foxcool** [tsenart/nap#3]
# github.com/tsenart/nap
../src/github.com/tsenart/nap/db.go:130: db.pdbs[i].SetConnMaxLifetime undefined (type *sql.DB has no field or method SetConnMaxLifetime)

deleting func (db *DB) SetConnMaxLifetime(d time.Duration)

fixes the problem

**Comment by tsenart** [comment]
You probably have an older version of Go. This `SetConnMaxLifetime` was introduced here: https://github.com/golang/go/commit/0c516c16328575ab78a4cce49874955dd590efa2

Upgrading your Go version should fix your problem.
